apiVersion: v1
kind: Service
metadata:
  name: {{ include "button-logger-app.fullname" . }}
  labels:
    {{- include "button-logger-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    {{- include "button-logger-app.selectorLabels" . | nindent 4 }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}