kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-for-button-logger-app
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: button-logger-app-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage-for-button-logger-app
  claimRef:
    name: button-logger-app-pv-claim
    namespace: button-logger-app
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/rke/stmp/rke-persistent-volumes/button-logger-app-pv/log"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: button-logger-app-pv-claim
  namespace: button-logger-app
spec:
  storageClassName: local-storage-for-button-logger-app
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi