apiVersion: v1
kind: Service
metadata:
  name: button-logger-app-service
  namespace: button-logger-app
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      #prometheus.io/port:   '8080'
spec:
  selector: 
    app: button-logger-application
  type: NodePort  
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32001
