apiVersion: v1
kind: Service
metadata:
  labels:
    app: button-logger-application
  name: button-logger-app-service
  namespace: button-logger-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
#  - name: https
#    port: 443
#    protocol: TCP
#    targetPort: 443
  selector:
    app: button-logger-application
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.66.102
  type: LoadBalancer